# Customer 360 - Data Overview

## Business Problem

The company wants to better understand its customers and make better decisions using customer data.

The main goals are to:

* Predict which customers are likely to **churn**.
* Predict each customer's **future 12-month revenue**.
* Group customers into different **customer segments**.
* Detect **unusual customer behavior**.
* Combine these results into one **Customer 360 view**.

This can help the company understand customer behavior, identify customers who may need attention, and better understand customer value.


## Project Objectives

In this project, we will:

* Explore and clean the customer data.
* Analyze customer behavior and identify important patterns.
* Build models to predict churn and future revenue.
* Segment customers using clustering.
* Detect unusual customers using anomaly detection.
* Use PCA to visualize customer patterns.
* Combine the ML results into a final Customer 360 table.

## Import Libraries

In [1]:
import pandas as pd 

import warnings
warnings.filterwarnings("ignore")

## Load Dataset

In [2]:
df = pd.read_csv('../data/raw/customer_360_ml_workshop.csv')

print(f'Shape : {df.shape}')
df.head()

Shape : (3000, 16)

,CustomerID,Age,Region,TenureMonths,ContractType,InternetType,MonthlyUsageGB,MonthlyChargeEGP,NumServices,SupportCalls6M,LatePayments12M,PaperlessBilling,AutoPay,SatisfactionScore,Future12MRevenueEGP,Churn
0,CUST-00001,22,Alexandria,23,Month-to-month,DSL,317.9,580.48,5,5,0,Yes,Yes,5.0,6287.08,Yes
1,CUST-00002,59,Upper Egypt,9,Month-to-month,4G/5G,359.3,434.36,1,1,1,No,Yes,4.0,4619.91,No
2,CUST-00003,52,Giza,21,Month-to-month,DSL,176.9,391.35,3,5,1,Yes,Yes,5.0,4512.25,No
3,CUST-00004,41,Giza,12,Month-to-month,DSL,312.5,420.40,3,2,1,No,Yes,5.0,3809.65,No
4,CUST-00005,40,Delta,21,Month-to-month,4G/5G,191.6,462.73,3,4,0,No,Yes,3.0,4731.09,No

## Data Understanding

### Columns

In [3]:
df.columns.to_list()

['CustomerID',
 'Age',
 'Region',
 'TenureMonths',
 'ContractType',
 'InternetType',
 'MonthlyUsageGB',
 'MonthlyChargeEGP',
 'NumServices',
 'SupportCalls6M',
 'LatePayments12M',
 'PaperlessBilling',
 'AutoPay',
 'SatisfactionScore',
 'Future12MRevenueEGP',
 'Churn']

### Data Information

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CustomerID           3000 non-null   object
 1   Age                  3000 non-null   int64
 2   Region               3000 non-null   object
 3   TenureMonths         3000 non-null   int64
 4   ContractType         3000 non-null   object
 5   InternetType         2955 non-null   object
 6   MonthlyUsageGB       2925 non-null   float64
 7   MonthlyChargeEGP     3000 non-null   float64
 8   NumServices          3000 non-null   int64
 9   SupportCalls6M       3000 non-null   int64
 10  LatePayments12M      3000 non-null   int64
 11  PaperlessBilling     3000 non-null   object
 12  AutoPay              3000 non-null   object
 13  SatisfactionScore    2940 non-null   float64
 14  Future12MRevenueEGP  3000 non-null   float64
 15  Churn                3000 non-null   object
dtypes: float64(4), int64(5), object(7)
memory usage: 375.1+ KB

### Statistical summary

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,3000.0,44.057667,15.346319,18.00,31.0000,44.000,57.0000,70.00
TenureMonths,3000.0,25.540667,16.525739,1.00,13.0000,22.000,35.0000,72.00
MonthlyUsageGB,2925.0,230.132855,89.357331,10.00,169.5000,228.700,290.4000,597.90
MonthlyChargeEGP,3000.0,487.345707,118.451753,142.40,398.9925,484.995,574.5725,866.99
NumServices,3000.0,3.515000,1.714085,1.00,2.0000,4.000,5.0000,6.00
SupportCalls6M,3000.0,2.206333,1.503722,0.00,1.0000,2.000,3.0000,9.00
LatePayments12M,3000.0,1.111000,1.066016,0.00,0.0000,1.000,2.0000,6.00
SatisfactionScore,2940.0,3.486054,1.013758,1.00,3.0000,4.000,4.0000,5.00
Future12MRevenueEGP,3000.0,5361.156050,1479.868751,1529.37,4330.7925,5274.620,6314.4975,11095.19

### Unique values

In [6]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values")

CustomerID: 3000 unique values
Age: 53 unique values
Region: 5 unique values
TenureMonths: 72 unique values
ContractType: 3 unique values
InternetType: 3 unique values
MonthlyUsageGB: 1920 unique values
MonthlyChargeEGP: 2893 unique values
NumServices: 6 unique values
SupportCalls6M: 10 unique values
LatePayments12M: 7 unique values
PaperlessBilling: 2 unique values
AutoPay: 2 unique values
SatisfactionScore: 5 unique values
Future12MRevenueEGP: 2989 unique values
Churn: 2 unique values

In [7]:
unique_values_cols = ['Region','ContractType','InternetType','AutoPay','Churn']

for col in unique_values_cols:
    print(f'{df[col].value_counts()}')
    print()

Region
Cairo          983
Giza           597
Delta          539
Alexandria     469
Upper Egypt    412
Name: count, dtype: int64

ContractType
Month-to-month    1680
One year           814
Two year           506
Name: count, dtype: int64

InternetType
Fiber    1350
DSL       824
4G/5G     781
Name: count, dtype: int64

AutoPay
Yes    1684
No     1316
Name: count, dtype: int64

Churn
No     2456
Yes     544
Name: count, dtype: int64

### Target Analysis

In [8]:
churn_percentage = df['Churn'].value_counts(normalize= True) * 100
print(churn_percentage.round(2))

Churn
No     81.87
Yes    18.13
Name: proportion, dtype: float64

## Dataset Column Description

The dataset contains customer demographic, subscription, usage, service, payment, satisfaction, churn, and future revenue information. Each row represents one customer.

| Column                  | Description                                                                                                                                                                                                          |
| ----------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `CustomerID`          | Unique ID for each customer.|
| `Age`                 | Customer's age.                                                                                |
| `Region`              | Customer's region.|
| `TenureMonths`        | Number of months the customer has been with the company.                                                                           |
| `ContractType`        | Customer's contract type.                                                 |
| `InternetType`        | Type of internet service used by the customer.                                                                |
| `MonthlyUsageGB`      | Customer's monthly internet usage in GB.                                                                                          |
| `MonthlyChargeEGP`    | Customer's monthly charge in Egyptian Pounds.                                                                      |
| `NumServices`         | Number of services used by the customer.                                                                      |
| `SupportCalls6M`      | Number of support calls in the last 6 months.                                                          |
| `LatePayments12M`     | Number of late payments in the last 12 months.                                                                                   |
| `SatisfactionScore`   | Customer satisfaction score.                                                                                    |
| `AutoPay`             | Whether the customer uses automatic payment.                                                                                |
| `Churn`               | Whether the customer left the service. Used as the classification target.                                                           |
| `Future12MRevenueEGP` | Customer's revenue over the next 12 months. Used as the regression target. |

### Target Variables

This project contains two supervised learning tasks:

* **Churn Classification:** Predict whether a customer will churn using `Churn` as the target.
* **Revenue Regression:** Predict the customer's future 12-month revenue using `Future12MRevenueEGP` as the target.

### Identifier Column

`CustomerID` is retained for customer-level reporting and for constructing the final **Customer 360** table, but it is excluded from machine learning models because it is an identifier rather than a meaningful predictive feature.